agent:
  id: ????????-????-????-????-???????????? # Replace with your ID
  api_key: ????????-????-????-????-???????????? # Replace with your secret key
master:
  url: https://domain.tld/api/metrics/ # Replace "domain.tld" with your master domain
# url: http://192.168.100.1/monitoring/api/metrics # uncoment this if master don't have any domains
  timeout: 5
metrics:
  cpu: true
  ram: true
  disk: true
  network: true
  system: true
  load_avg: true
agent_runtime:
  interval_seconds: 10
  retry_attempts: 3
  retry_delay: 2
config_version: '1'
